Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 79, in <module>
    import os
  File "/usr/lib/python3.8/os.py", line 27, in <module>
    import stat as st
  File "/usr/lib/python3.8/stat.py", line 193, in <module>
    from _stat import *
  File "<frozen importlib._bootstrap>", line 988, in _find_and_load
  File "<frozen importlib._bootstrap>", line 148, in __enter__
  File "<frozen importlib._bootstrap>", line 163, in _get_module_lock
KeyboardInterrupt
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 597, in <module>
    main()
  File "/usr/lib/python3.8/site.py", line 583, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/lib/python3.8/site.py", line 322, in addusersitepackages
    addsitedir(user_site, known_paths)
  File "/usr/lib/python3.8/site.py", line 214, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.8/site.py", line 175, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 79, in <module>
    import os
  File "/usr/lib/python3.8/os.py", line 29, in <module>
    from _collections_abc import _check_methods
  File "/usr/lib/python3.8/_collections_abc.py", line 173, in <module>
    class AsyncIterator(AsyncIterable):
  File "/usr/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
KeyboardInterrupt
